-- Created by Ebean DDL
-- To stop Ebean DDL generation, remove this comment (both lines) and start using Evolutions

-- !Ups

-- apply changes
create table citizen_idmodel (
  id                            bigint generated by default as identity not null,
  age                           integer not null,
  mobileno                      bigint,
  studentmodel                  bigint,
  name                          varchar(255),
  address                       varchar(255),
  constraint uq_citizen_idmodel_studentmodel unique (studentmodel),
  constraint pk_citizen_idmodel primary key (id)
);

create table student_model (
  id                            bigint generated by default as identity not null,
  age                           integer not null,
  name                          varchar(255),
  constraint pk_student_model primary key (id)
);

-- foreign keys and indices
alter table citizen_idmodel add constraint fk_citizen_idmodel_studentmodel foreign key (studentmodel) references student_model (id) on delete restrict on update restrict;


-- !Downs

-- drop all foreign keys
alter table if exists citizen_idmodel drop constraint if exists fk_citizen_idmodel_studentmodel;

-- drop all
drop table if exists citizen_idmodel cascade;

drop table if exists student_model cascade;

